### ISSUE TITLE
TypeError: object if type 'filter' hs no len() in winregrc/sam.py

### ISSUE THREAD

**Issue by GREEKYnikhilsharma** [libyal/winreg-kb#5]
I am running winregrc/sam.py file in python 3.5.4 windows.
Getting this error.
Traceback (most recent call last):
  File "sam.py", line 113, in <module>
    class SecurityAccountManagerDataParser(object):
  File "sam.py", line 289, in SecurityAccountManagerDataParser
    yaml_definition=_DATA_TYPE_FABRIC_DEFINITION)
  File "C:\Users\hp pc\AppData\Local\Programs\Python\Python35\lib\site-packages\dtfabric\runtime\fabric.py", line 26, in __init__
    definitions_reader.ReadFileObject(definitions_registry, file_object)
  File "C:\Users\hp pc\AppData\Local\Programs\Python\Python35\lib\site-packages\dtfabric\reader.py", line 857, in ReadFileObject
    definitions_registry, yaml_definition)
  File "C:\Users\hp pc\AppData\Local\Programs\Python\Python35\lib\site-packages\dtfabric\reader.py", line 778, in _ReadDefinition
    return data_type_callback(definitions_registry, definition_values, name)
  File "C:\Users\hp pc\AppData\Local\Programs\Python\Python35\lib\site-packages\dtfabric\reader.py", line 687, in _ReadStructureDataTypeDefinition
    definition_name)
  File "C:\Users\hp pc\AppData\Local\Programs\Python\Python35\lib\site-packages\dtfabric\reader.py", line 166, in _ReadDataTypeDefinitionWithMembers
    definitions_registry, member, definition_object.name)
  File "C:\Users\hp pc\AppData\Local\Programs\Python\Python35\lib\site-packages\dtfabric\reader.py", line 493, in _ReadMemberDataTypeDefinitionMember
    if len(type_values) > 1:
TypeError: object of type 'filter' has no len()

**Comment by joachimmetz** [comment]
This looks like an issue in dtfabric I'll have a look when time permits
