### ISSUE TITLE
Fix issue with appcompatcache.py

### ISSUE THREAD

**Issue by joachimmetz** [libyal/winreg-kb#7]
```
Traceback (most recent call last):
  File "winreg-kb/scripts/appcompatcache.py", line 98, in <module>
    if not Main():
  File "winreg-kb/scripts/appcompatcache.py", line 88, in Main
    all_control_sets=options.all_control_sets)
  File "winreg-kb/winregrc/appcompatcache.py", line 1152, in Collect
    app_compat_cache_key, output_writer):
  File "winreg-kb/winregrc/appcompatcache.py", line 1082, in _CollectAppCompatCacheFromKey
    cached_entry_size)
  File "winreg-kb/winregrc/appcompatcache.py", line 976, in ParseCachedEntry
    data_offset = cached_entry.data_offset
AttributeError: 'appcompatcache_cached_entry_7_64bit' object has no attribute 'data_offset'
```

**Comment by joachimmetz** [comment]
data_size and data_offset missing from appcompatcache_cached_entry_7_64bit

**Comment by joachimmetz** [comment]
Also address

```
Traceback (most recent call last):
  File "winreg-kb/scripts/appcompatcache.py", line 98, in <module>
    if not Main():
  File "winreg-kb/scripts/appcompatcache.py", line 88, in Main
    all_control_sets=options.all_control_sets)
  File "winreg-kb/winregrc/appcompatcache.py", line 1156, in Collect
    app_compat_cache_key, output_writer):
  File "winreg-kb/winregrc/appcompatcache.py", line 1088, in _CollectAppCompatCacheFromKey
    output_writer.WriteCachedEntry(cached_entry)
  File "winreg-kb/scripts/appcompatcache.py", line 27, in WriteCachedEntry
    print('Type\t\t\t: {0:s}'.format(service_type_description))
NameError: global name 'service_type_description' is not defined

```
